### ISSUE TITLE
frontend-forms.css changes site font

### ISSUE THREAD

**Issue by LariElovainio** [weDevsOfficial/wp-user-frontend#1119]
```
body {
  font-family: 'Open Sans', sans-serif !important;
```

All my forms are set to use the theme stylesheet, yet this file is loaded, not sure if that’s an error, but the above snippet sure is problematic.

**Comment by mayeenulislam** [comment]
WordPress' default font-family declaration could be a wonderful solution here:

```css
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
}
```

The font overriding issue persists only when we are using the forms whether in add or edit mode.
